package com.jzeen.travel.core.util;

public class MailContentUtil {
    public static String buildUserRegMailContent(String userName, String webRoot, String url) {
        StringBuffer buffer = new StringBuffer();

        buffer.append("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">");
        buffer.append("<html>");
        buffer.append("<head>");
        buffer.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" >");
        buffer.append("<title>Welcome to the X2our</title>");
        buffer.append("<style type=\"text/css\">");
        buffer.append("html { -webkit-text-size-adjust:none; -ms-text-size-adjust: none;}");
        buffer.append("@media only screen and (max-device-width: 680px), only screen and (max-width: 680px) {");
        buffer.append("*[class=\"table_width_100\"] {");
        buffer.append("width: 96% !important;");
        buffer.append("}");
        buffer.append("*[class=\"border-right_mob\"] {");
        buffer.append("border-right: 1px solid #dddddd;");
        buffer.append("}");
        buffer.append("*[class=\"mob_100\"] {");
        buffer.append("width: 100% !important;");
        buffer.append("}");
        buffer.append("*[class=\"mob_center\"] {");
        buffer.append("text-align: center !important;");
        buffer.append("}");
        buffer.append("*[class=\"mob_center_bl\"] {");
        buffer.append("float: none !important;");
        buffer.append("display: block !important;");
        buffer.append("margin: 0px auto;");
        buffer.append("}");
        buffer.append(".iage_footer a {");
        buffer.append("text-decoration: none;");
        buffer.append("color: #929ca8;");
        buffer.append("}");
        buffer.append("img.mob_display_none {");
        buffer.append("width: 0px !important;");
        buffer.append("height: 0px !important;");
        buffer.append("display: none !important;");
        buffer.append("}");
        buffer.append("img.mob_width_50 {");
        buffer.append("width: 40% !important;");
        buffer.append("height: auto !important;");
        buffer.append("}");
        buffer.append("}");
        buffer.append(".table_width_100 {");
        buffer.append("width: 680px;");
        buffer.append("}");
        buffer.append("</style>");
        buffer.append("</head>");
        buffer.append("<body style=\"padding: 0px; margin: 0px;\">");
        buffer.append("<div id=\"mailsub\" class=\"notification\" align=\"center\">");
        buffer.append("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"min-width: 320px;\"><tr><td align=\"center\" bgcolor=\"#eff3f8\">");
        buffer.append("<table width=\"680\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
        buffer.append("<tr><td>");
        buffer.append("<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"table_width_100\" width=\"100%\" style=\"max-width: 680px; min-width: 300px;\">");
        buffer.append("<tr><td align=\"center\" bgcolor=\"#eff3f8\">");
        //buffer.append("<div style=\"height: 20px; line-height: 20px; font-size: 10px;\">&nbsp;</div>");
        buffer.append("<table width=\"96%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
        buffer.append("<tr><td align=\"left\">");
        buffer.append("<div class=\"mob_center_bl\" style=\"float: left; display: inline-block; width: 115px;\">");
        buffer.append("<table class=\"mob_center\" width=\"115\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\" style=\"border-collapse: collapse;\">");
        buffer.append("<tr><td align=\"left\" valign=\"middle\">");
        buffer.append("<div style=\"height: 15px; line-height: 5px; font-size: 10px;\">&nbsp;</div>");
        buffer.append("<table width=\"115\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" >");
        buffer.append("<tr><td align=\"left\" valign=\"top\" class=\"mob_center\">");
        buffer.append("<a href=\"#\" target=\"_blank\" style=\"color: #596167; font-family: Arial, Helvetica, sans-serif; font-size: 13px;\">");
        buffer.append("<font face=\"Arial, Helvetica, sans-seri; font-size: 13px;\" size=\"3\" color=\"#596167\">");
//       buffer.append("<img src=\"http://localhost:8018/assets/img/logo-corp-red.png\" width=\"115\" height=\"19\" alt=\"X2Our\" border=\"0\" style=\"display: block;\" /></font></a>");
        buffer.append("<img src=\"");
        buffer.append(webRoot);
        buffer.append("/assets/img/logo-corp-red.png\" alt=\"X2Our\" border=\"0\" style=\"display: block;\" /></font></a>");
        buffer.append("</td></tr>");
        buffer.append("</table>");
        buffer.append("</td></tr>");
        buffer.append("</table></div>");
        buffer.append("<div class=\"mob_center_bl\" style=\"float: right; display: inline-block; width: 88px;\">");
        buffer.append("<table width=\"88\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"right\" style=\"border-collapse: collapse;\">");
        buffer.append("<tr><td align=\"right\" valign=\"middle\">");
        buffer.append("<div style=\"height: 20px; line-height: 20px; font-size: 10px;\">&nbsp;</div>");
        buffer.append("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" >");
        buffer.append("<tr><td align=\"right\">");
        buffer.append("<div class=\"mob_center_bl\" style=\"width: 88px;\">");
        buffer.append("<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
        buffer.append("<tr>");
//       buffer.append("<td width=\"30\" align=\"center\" style=\"line-height: 19px;\">");
//       buffer.append("<a href=\"#\" target=\"_blank\" style=\"color: #596167; font-family: Arial, Helvetica, sans-serif; font-size: 12px;\">");
//       buffer.append("<font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#596167\">");
//       buffer.append("<img src=\"http://localhost:8018/assets/img/footer-zhongxin-travel.png\" alt=\"中信旅游战略合作伙伴\" border=\"0\" style=\"display: block;\" /></font></a>");
//       buffer.append("</td><td width=\"39\" align=\"center\" style=\"line-height: 19px;\">");
//       buffer.append("<a href=\"#\" target=\"_blank\" style=\"color: #596167; font-family: Arial, Helvetica, sans-serif; font-size: 12px;\">");
//       buffer.append("<font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#596167\">");
//       buffer.append("<img src=\"http://localhost:8018/assets/img/footer-alipay.png\" alt=\"支付宝\" border=\"0\" style=\"display: block;\" /></font></a>");
//       buffer.append("</td><td width=\"29\" align=\"right\" style=\"line-height: 19px;\">");
//       buffer.append("<a href=\"#\" target=\"_blank\" style=\"color: #596167; font-family: Arial, Helvetica, sans-serif; font-size: 12px;\">");
//       buffer.append("<font face=\"Arial, Helvetica, sans-serif\" size=\"2\" color=\"#596167\">");
//       buffer.append("<img src=\"http://localhost:8018/assets/img/footer-guangzhou-gongshang.png\"  alt=\"广州工商\" border=\"0\" style=\"display: block;\" /></font></a>");
//       buffer.append("</td>");
        buffer.append("</tr>");
        buffer.append("</table>");
        buffer.append("</div>");
        buffer.append("</td></tr>");
        buffer.append("</table>");
        buffer.append("</td></tr>");
        buffer.append("</table></div></td>");
        buffer.append("</tr>");
        buffer.append("</table>");
        buffer.append("<div style=\"height: 15px; line-height: 5px; font-size: 10px;\">&nbsp;</div>");
        buffer.append("</td></tr>");
        buffer.append("<tr><td align=\"center\" bgcolor=\"#ffffff\">");
        buffer.append("<table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
        buffer.append("<tr><td align=\"center\">");
        buffer.append("<div style=\"height: 50px; line-height: 80px; font-size: 10px;\">&nbsp;</div>");
        buffer.append("<div style=\"line-height: 44px;\">");
        buffer.append("<font face=\"Arial, Helvetica, sans-serif\" size=\"5\" color=\"#57697e\" style=\"font-size: 34px;\">");
        buffer.append("<span style=\"font-family: Arial, Helvetica, sans-serif; font-size: 34px; color: #57697e;\">");
//        buffer.append("Welcome to the X2our");
        buffer.append("注册成功，请在下面验证您的邮箱。");
        buffer.append("</span></font>");
        buffer.append("</div>");
        buffer.append("<div style=\"height: 30px; line-height: 30px; font-size: 10px;\">&nbsp;</div>");
        buffer.append("</td></tr>");
        buffer.append("<tr><td align=\"center\">");
        buffer.append("<div style=\"line-height: 30px;\">");
        buffer.append("<font face=\"Arial, Helvetica, sans-serif\" size=\"5\" color=\"#4db3a4\" style=\"font-size: 17px;\">");
        buffer.append("<span style=\"font-family: Arial, Helvetica, sans-serif; font-size: 17px; font-weight：bold; color: #4db3a4;\">");
        buffer.append("Hi ");
        buffer.append(userName);
        buffer.append("， 欢迎您加入西游网！");
        buffer.append("</span></font>");
        buffer.append("</div>");
        buffer.append("<div style=\"height: 35px; line-height: 35px; font-size: 10px;\">&nbsp;</div>");
        buffer.append("</td></tr>");
        buffer.append("<tr><td align=\"center\">");
        buffer.append("<table width=\"80%\" align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
        buffer.append("<tr><td align=\"center\">");
        buffer.append("<div style=\"line-height: 24px;\">");
        buffer.append("<font face=\"Arial, Helvetica, sans-serif\" size=\"4\" color=\"#57697e\" style=\"font-size: 16px;\">");
        buffer.append("<span style=\"font-family: Arial, Helvetica, sans-serif; font-size: 18px; font-weight：bold; color: #57697e;\">");
        buffer.append("一个独一无二的旅程由此开始......");
//        buffer.append("西游网");
//        buffer.append("</span>");
//        buffer.append("<span style=\"font-family: Arial, Helvetica, sans-serif; font-size: 15px; color: #57697e;\">");
//        buffer.append("<br>拥有上百位专业的境外导游，<br>十多位资深的旅游规划师，<br>大量独有的旅游资源，国内领先；<br>直接对接国外供应链，价格实惠；<br>中信旅游战略合作伙伴，值得信赖&nbsp;！");
//        buffer.append("</span>");
//        buffer.append("<span style=\"font-family: Arial, Helvetica, sans-serif; font-size: 18px; font-weight：bold; color: #57697e;\">");
//        buffer.append("<br>西游网");
//        buffer.append("</span>");
//        buffer.append("<span style=\"font-family: Arial, Helvetica, sans-serif; font-size: 15px; color: #57697e;\">");
//        buffer.append("<br>是您的私人定制旅行专家，<br>为您量身订做个性化的旅行规划，<br>向您提供全程一站式的贴心服务，<br>为您打造一个专属的难忘旅程&nbsp;！<br>成为西游网用户，开始您与众不同的旅行吧！");
        buffer.append("</span></font>");
        buffer.append("</div>");
        buffer.append("</td></tr>");
        buffer.append("</table>");
        buffer.append("<div style=\"height: 45px; line-height: 45px; font-size: 10px;\">&nbsp;</div>");
        buffer.append("</td></tr>");
        buffer.append("<tr><td align=\"center\">");
        buffer.append("<div style=\"line-height:24px;\">");
//       buffer.append("<a href=\"#\" target=\"_blank\" style=\"color: #596167; font-family: Arial, Helvetica, sans-serif; font-size: 13px;\">");
        buffer.append("<a href=\"");
        buffer.append(url);//用户图片的超链接。
        buffer.append("\" target=\"_blank\" style=\"color: #596167; font-family: Arial, Helvetica, sans-serif; font-size: 13px;\">");
        buffer.append("<font face=\"Arial, Helvetica, sans-seri; font-size: 13px;\" size=\"3\" color=\"#596167\">");
        buffer.append("<img src=\"");
        buffer.append(webRoot);//用于规定图片的访问地址，不添加的话就找不到图片。
        buffer.append("/assets/img/x2our-youxiang-jihuo.png\" alt=\"|\" class=\"mob_display_none\" /></a>&nbsp;&nbsp;&nbsp;&nbsp;");
        buffer.append("</div>");
        buffer.append("<div style=\"height: 50px; line-height: 80px; font-size: 10px;\">&nbsp;</div>");
        buffer.append("</td></tr>");
        buffer.append("</table>");
        buffer.append("</td></tr>");
        buffer.append("<tr><td align=\"center\" bgcolor=\"#f9fafc\">");
        buffer.append("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
        buffer.append("<tr><td align=\"center\">");
        buffer.append("<div style=\"height: 5px; line-height: 5px; font-size: 10px;\">&nbsp;</div>");
        buffer.append("<table width=\"80%\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">");
        buffer.append("<tr>");
        buffer.append("<td align=\"center\" valign=\"middle\" style=\"font-size: 12px; line-height:22px;\">");
        buffer.append("<font face=\"Tahoma, Arial, Helvetica, sans-serif\" size=\"2\" color=\"#282f37\" style=\"font-size: 12px;\">");
        buffer.append("<span style=\"font-family: Arial, Helvetica, sans-serif; font-size: 12px; color: #5b9bd1;\">");
//       buffer.append("<a href=\"#\" target=\"_blank\" style=\"color: #5b9bd1; text-decoration: none;\">关注微信，红包不断，惊喜连连</a>");
        buffer.append("<p style=\"color: #5b9bd1; text-decoration: none;\">关注微信，红包不断，惊喜连连.</p>");
        buffer.append("&nbsp;&nbsp;&nbsp;&nbsp;<img src=\"");
        buffer.append(webRoot);
        buffer.append("/assets/img/x2our-weichat.jpg\" alt=\"|\" class=\"mob_display_none\" /></a>&nbsp;&nbsp;&nbsp;&nbsp;");
        buffer.append("</span></font>");
        buffer.append("</td>");
        buffer.append("</tr>");
        buffer.append("</table>");
        buffer.append("</td></tr>");
        buffer.append("<tr><td><div style=\"height: 30px; line-height: 30px; font-size: 10px;\">&nbsp;</div></td></tr>");
        buffer.append("</table>");
        buffer.append("</td></tr>");
        buffer.append("<tr><td class=\"iage_footer\" align=\"center\" bgcolor=\"#eff3f8\">");
        buffer.append("<div style=\"height: 40px; line-height: 40px; font-size: 10px;\">&nbsp;</div>");
        buffer.append("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
        buffer.append("<tr><td align=\"center\">");
        buffer.append("<font face=\"Arial, Helvetica, sans-serif\" size=\"3\" color=\"#96a5b5\" style=\"font-size: 13px;\">");
        buffer.append("<span style=\"font-family: Arial, Helvetica, sans-serif; font-size: 13px; color: #96a5b5;\">");
        buffer.append("2015 © 广州西游信息科技有限公司. ALL Rights Reserved.");
        buffer.append("</span></font>");
        buffer.append("</td></tr>");
        buffer.append("</table>");
        buffer.append("<div style=\"height: 50px; line-height: 50px; font-size: 10px;\">&nbsp;</div>");
        buffer.append("</td></tr>");
        buffer.append("</table>");
        buffer.append("</td></tr>");
        buffer.append("</table>");
        buffer.append("</td></tr>");
        buffer.append("</table>");
        buffer.append("</div>");
        buffer.append("</body>");
        buffer.append("</html>");

        return buffer.toString();
    }
}
